### PR TITLE
ENH: Added missing extensions

### PR DESCRIPTION
**Pull request by cpinter**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks :+1:

**Comment by fbudin69500** [comment]
Should this repository be forked in the Slicer repository?

**Comment by jcfr** [comment]
> Should this repository be forked in the Slicer repository?

Since you an active member of the Slicer community and the original author, keeping it under your username makes sense.

That said if you want to offload its maintenance, I would prefer you transfer it to the Slicer organization instead of just forking it.

**Comment by fbudin69500** [comment]
Either way works for me. I know that ITK remote modules are typically forked on the InsightSoftwareConsortium github account. I was just not sure if the same policy applied to Slicer :)

**Pull request merged**
