### PR TITLE
Add 4.8 and 4.8.1 version numbers to ExtensionStats

### PR DESCRIPTION
**Pull request by ihnorton**
cc @ljod

### CODE REVIEW

**Comment by ihnorton** [comment]
cc @lassoan too

**Comment by jcfr** [comment]
Thanks. 👍 

Also added a step in the release process of Slicer. see https://www.slicer.org/wiki/Documentation/Nightly/Developers/ReleaseProcess#Update_ExtensionStats_extension

**Comment by jcfr** [comment]
@ljod For reference, dates and revisions are all available here: https://www.slicer.org/wiki/Release_Details   (slicer wiki -> Developer manual -> Resources -> Release Details)

**Comment by ljod** [comment]
Thanks everyone this is great.

**Pull request merged**
